#macro = SSE
$SHOW_SCENE=false
$SHOW_STATUS=false

#source = db1.conf
select random(999999999) as proc_id

#source = db1.conf
select 'SSETMATU IS NOT NULL' as filtro,
	   '@$MULTIOP{ (SSETMATU, SSENNNUMSOL) >= (''@DATA_ATUALIZACAO::native'', @NUMEROSOLICITACAO) }' as partida;
  
#source = db2-4200-H.conf
$REPEAT_WHILE_FOUND=true

select
SSENNNUMSOL AS numerosolicitacao,
SSECDTPS AS tiposolicitacao,
SSECDESP AS codespecificacao,
0 AS tipopessoa,
0 AS cpfcnpjsolicitante,
0 AS dddsolicitante,
SSENNFONESOL AS telefonesolicitante,
'' AS ramalsolicitante,
SSENNCLI AS numerodocliente,
0 AS codvinculosolicitante,
0 AS CODTIPOORIGEMSOLICITACAO,
SSECDMSO AS CODMOTIVOSOLICITACAO,
SSECDSITSOL AS SITUACAOSOLICITACAO,
SSEICATENDIDA AS INDICADORATENDIDA,
SSECDRAT AS CODIGORATEIO,
SSEDTHRSOL AS DATAHORASOLICITACAO,
SSEDTHRFIMEXEC AS DATAHORAFIMEXECUCAO,
SSEDTHRCONCL AS DATAHORACONCLUSAO,
SSECDUNT AS CODUNIDADEANTERIOR,
SSECDUNDSOL AS CODUNIDADESOLICITANTE,
SSECDUNDDEST AS UNIDADEDESTINO,
SSECDUNDATUAL AS UNIDADEATUAL,
SSENNMATUSU AS MATRICULA,
SSECDLOC AS LOCALIDADE,
SSECDSFT AS SETORFATURAMENTO,
SSENNQUADRA AS QUADRA,
SSECDBAIRRO AS BAIRRO,
SSECDLOG AS LOGRADOURO,
SSENNIMOVEL AS PORTA,
SSENNCEP AS CEP,
SSECDMUN AS MUNICIPIO,
SSECDTPA AS TIPOAREA,
SSECDBES AS CODESGOTOSANITARIO,
SSECDLCR AS CODLOCALOCORRENCIA,
SSECDPRU AS PAVIMENTORUA,
SSECDPCA AS PAVIMENTOCALCADA,
SSEDTPREVINIC AS DATAPREVISAOINICIAL,
SSEDTPREVATU AS DATAPREVISAOATUAL,
SSEQTDHRATD qtd_horas_servico,
SSECDMRA AS MOTIVO_REABERTURA_SS,
SSECDSMC AS MOTIVO_CANCELAMENTO,
SSENNNUMSOLVINC AS NUMERO_SOLIC_VINCULADA,
SSECDFUNATU AS MAT_FUNCIONARIO_ATUALIZOU,
SSEDTSOL AS DATA_SOLICITACAO,
SSEDTCONCL AS DATA_CONCLUSAO,
SSEEDCOMPL AS COMPLEMENTO_ENDERECO,
SSEDSPTOREF AS PONTO_REFERENCIA,
SSEDSEMAILSOL AS EMAIL_SOLICITANTE,
SSEDSOBS AS OBSEVACAO,
SSEQTSOLREC AS QTD_SOLIC_RECEBIDA,
SSEQTSOLVINC AS QTD_SOL_VINCULADAS,
SSENNNUMSOLREAT AS NUM_SOLIC_REATIVADA,
SSECDFUNREG AS FUNCINOARIO_REGISTROU,
SSETMATU AS DATA_ATUALIZACAO,
SSEDTHRREG AS DATA_HORA_REGISTRO,
SSETMPATD AS MEDIA_ATENDIMENTO,
SSECDSUP AS COD_SUPERINT,
SSECDPAD AS POLO_ADM,
SSENNPRAZO AS PRAZO_ATENDIMENTO,
SSEABERTESPEC AS TIPO_ABERTURA_ESPECIFICA,
SSECDUNTATUAL AS UNIDADE_ATUA_SOLICITACAO
from BIADM.SCITSSE
where @filtro::native
      @query=db1.conf{select ' and ('||condicaopartida||')' from dof_processoatualizacao
                      where tipo = 9 and escopo = @filtro order by id desc limit 1 }::native
      and SSETMATU > '2018-08-20 18:18:33.193879'					  
order by SSETMATU
fetch first 20000 rows only

#iffound=10  
repeat;

#ifnotfound  
stop;

#target = db1.conf
$BATCH_SIZE=20000
$SHOW_SQL=false
$LABEL=INSERT @#rowid: NUMEROSOLICITACAO=@NUMEROSOLICITACAO SSETMATU=@DATA_ATUALIZACAO

insert into dof_servicos (
    NUMEROSOLICITACAO,TIPOSOLICITACAO,codespecificacao,TIPOPESSOA,CPFCNPJSOLICITANTE,DDDSOLICITANTE,TELEFONESOLICITANTE,RAMALSOLICITANTE,
    NUMERODOCLIENTE,CODVINCULOSOLICITANTE,CODTIPOORIGEMSOLICITACAO,CODMOTIVOSOLICITACAO,SITUACAOSOLICITACAO,INDICADORATENDIDA,CODIGORATEIO,DATAHORASOLICITACAO,
    DATAHORAFIMEXECUCAO,DATAHORACONCLUSAO,CODUNIDADEANTERIOR,CODUNIDADESOLICITANTE,UNIDADEDESTINO,UNIDADEATUAL,MATRICULA,LOCALIDADE,SETORFATURAMENTO,QUADRA,BAIRRO,
    LOGRADOURO,PORTA,CEP,MUNICIPIO,TIPOAREA,CODESGOTOSANITARIO,CODLOCALOCORRENCIA,PAVIMENTORUA,PAVIMENTOCALCADA,DATAPREVISAOINICIAL,DATAPREVISAOATUAL,qtd_horas_servico,
    MOTIVO_REABERTURA_SS,MOTIVO_CANCELAMENTO,NUMERO_SOLIC_VINCULADA,MAT_FUNCIONARIO_ATUALIZOU,DATA_SOLICITACAO,DATA_CONCLUSAO,COMPLEMENTO_ENDERECO,PONTO_REFERENCIA,EMAIL_SOLICITANTE,
    OBSEVACAO,QTD_SOLIC_RECEBIDA,QTD_SOL_VINCULADAS,NUM_SOLIC_REATIVADA,FUNCINOARIO_REGISTROU,DATA_ATUALIZACAO,DATA_HORA_REGISTRO,MEDIA_ATENDIMENTO,COD_SUPERINT,POLO_ADM,
    PRAZO_ATENDIMENTO,TIPO_ABERTURA_ESPECIFICA,UNIDADE_ATUA_SOLICITACAO	
) values (
    @NUMEROSOLICITACAO,@TIPOSOLICITACAO,@codespecificacao,@TIPOPESSOA,@CPFCNPJSOLICITANTE,@DDDSOLICITANTE,@TELEFONESOLICITANTE,@RAMALSOLICITANTE,
    @NUMERODOCLIENTE,@CODVINCULOSOLICITANTE,@CODTIPOORIGEMSOLICITACAO,@CODMOTIVOSOLICITACAO,@SITUACAOSOLICITACAO,@INDICADORATENDIDA,@CODIGORATEIO,@DATAHORASOLICITACAO,
    @DATAHORAFIMEXECUCAO,@DATAHORACONCLUSAO,@CODUNIDADEANTERIOR,@CODUNIDADESOLICITANTE,@UNIDADEDESTINO,@UNIDADEATUAL,@MATRICULA,@LOCALIDADE,@SETORFATURAMENTO,@QUADRA,@BAIRRO,
    @LOGRADOURO,@PORTA,@CEP,@MUNICIPIO,@TIPOAREA,@CODESGOTOSANITARIO,@CODLOCALOCORRENCIA,@PAVIMENTORUA,@PAVIMENTOCALCADA,@DATAPREVISAOINICIAL,@DATAPREVISAOATUAL,@qtd_horas_servico,
    @MOTIVO_REABERTURA_SS,@MOTIVO_CANCELAMENTO,@NUMERO_SOLIC_VINCULADA,@MAT_FUNCIONARIO_ATUALIZOU,@DATA_SOLICITACAO,@DATA_CONCLUSAO,@COMPLEMENTO_ENDERECO,@PONTO_REFERENCIA,@EMAIL_SOLICITANTE,
    @OBSEVACAO,@QTD_SOLIC_RECEBIDA,@QTD_SOL_VINCULADAS,@NUM_SOLIC_REATIVADA,@FUNCINOARIO_REGISTROU,@DATA_ATUALIZACAO,@DATA_HORA_REGISTRO,@MEDIA_ATENDIMENTO,@COD_SUPERINT,@POLO_ADM,
    @PRAZO_ATENDIMENTO,@TIPO_ABERTURA_ESPECIFICA,@UNIDADE_ATUA_SOLICITACAO
) 

#afterlast = db1.conf
$RECURSIVE_REFERENCE=true
insert into dof_processoatualizacao (tipo, escopo, updatedregistro, registros, condicaopartida, proc_id)
values (9, @filtro, @DATA_ATUALIZACAO, @#rowid, @partida, @proc_id);