package perdas.model;
// Generated 22/02/2019 16:25:43 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.NotBlank;

/**
 * DimensaoTempo generated by hbm2java
 */
@Entity(name="tempo")
public class DimensaoTempo  implements Serializable {

	 private static final long serialVersionUID = 1L;
     
	 public int getIdTempo() {
		return idTempo;
	}
	public Date getDataDia() {
		return dataDia;
	}
	public Integer getAno() {
		return ano;
	}
	public Integer getMes() {
		return mes;
	}
	public String getNomeMes() {
		return nomeMes;
	}
	public Integer getDia() {
		return dia;
	}
	public Integer getDiadoano() {
		return diadoano;
	}
	public String getDiaSemana() {
		return diaSemana;
	}
	public String getAnoMesRef() {
		return anoMesRef;
	}
	public Date getInicioSemana() {
		return inicioSemana;
	}
	public Date getFinalSemana() {
		return finalSemana;
	}
	public Date getInicioMes() {
		return inicioMes;
	}
	public Date getFinalMes() {
		return finalMes;
	}
	@Id
	 @NotBlank(message="{notblank}")	
     private int idTempo;
     @Column
     private Date dataDia;
     @Column
     private Integer ano;
     @Column
     private Integer mes;
     @Column
     private String nomeMes;
     @Column
     private Integer dia;
     @Column
     private Integer diadoano;
     @Column
     private String diaSemana;
     @Column
     private String anoMesRef;
     @Column
     private Date inicioSemana;
     @Column
     private Date finalSemana;
     @Column
     private Date inicioMes;
     @Column
     private Date finalMes;

    /*public DimensaoTempo() {
    }

	
    public DimensaoTempo(Date dataDia, int idTempo) {
        this.dataDia = dataDia;
        this.idTempo = idTempo;
    }
    public DimensaoTempo(Date dataDia, int idTempo, Integer ano, Integer mes, String nomeMes, Integer dia, Integer diadoano, String diaSemana, String anoMesRef, Date inicioSemana, Date finalSemana, Date inicioMes, Date finalMes, Set dimensaoVazamentos) {
       this.dataDia = dataDia;
       this.idTempo = idTempo;
       this.ano = ano;
       this.mes = mes;
       this.nomeMes = nomeMes;
       this.dia = dia;
       this.diadoano = diadoano;
       this.diaSemana = diaSemana;
       this.anoMesRef = anoMesRef;
       this.inicioSemana = inicioSemana;
       this.finalSemana = finalSemana;
       this.inicioMes = inicioMes;
       this.finalMes = finalMes;
       this.dimensaoVazamentos = dimensaoVazamentos;
    }
   
    public Date getDataDia() {
        return this.dataDia;
    }
    
    public void setDataDia(Date dataDia) {
        this.dataDia = dataDia;
    }
    public int getIdTempo() {
        return this.idTempo;
    }
    
    public void setIdTempo(int idTempo) {
        this.idTempo = idTempo;
    }
    public Integer getAno() {
        return this.ano;
    }
    
    public void setAno(Integer ano) {
        this.ano = ano;
    }
    public Integer getMes() {
        return this.mes;
    }
    
    public void setMes(Integer mes) {
        this.mes = mes;
    }
    public String getNomeMes() {
        return this.nomeMes;
    }
    
    public void setNomeMes(String nomeMes) {
        this.nomeMes = nomeMes;
    }
    public Integer getDia() {
        return this.dia;
    }
    
    public void setDia(Integer dia) {
        this.dia = dia;
    }
    public Integer getDiadoano() {
        return this.diadoano;
    }
    
    public void setDiadoano(Integer diadoano) {
        this.diadoano = diadoano;
    }
    public String getDiaSemana() {
        return this.diaSemana;
    }
    
    public void setDiaSemana(String diaSemana) {
        this.diaSemana = diaSemana;
    }
    public String getAnoMesRef() {
        return this.anoMesRef;
    }
    
    public void setAnoMesRef(String anoMesRef) {
        this.anoMesRef = anoMesRef;
    }
    public Date getInicioSemana() {
        return this.inicioSemana;
    }
    
    public void setInicioSemana(Date inicioSemana) {
        this.inicioSemana = inicioSemana;
    }
    public Date getFinalSemana() {
        return this.finalSemana;
    }
    
    public void setFinalSemana(Date finalSemana) {
        this.finalSemana = finalSemana;
    }
    public Date getInicioMes() {
        return this.inicioMes;
    }
    
    public void setInicioMes(Date inicioMes) {
        this.inicioMes = inicioMes;
    }
    public Date getFinalMes() {
        return this.finalMes;
    }
    
    public void setFinalMes(Date finalMes) {
        this.finalMes = finalMes;
    }
    public Set getDimensaoVazamentos() {
        return this.dimensaoVazamentos;
    }
    
    public void setDimensaoVazamentos(Set dimensaoVazamentos) {
        this.dimensaoVazamentos = dimensaoVazamentos;
    }

*/


}


