package perdas.model;
// Generated 22/02/2019 16:25:43 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.NotBlank;

/**
 * DimensaoVazamento generated by hbm2java
 */
@Entity(name="registro_vazamento")
public class RegistroVazamento  implements Serializable {

	private static final long serialVersionUID = 1L;
	
	public int getIdVaz() {
		return idVaz;
	}
	public Integer getNumerosolicitacao() {
		return numerosolicitacao;
	}
	public Integer getTiposolicitacao() {
		return tiposolicitacao;
	}
	public Integer getCodespecificacao() {
		return codespecificacao;
	}
	public Integer getRegiao() {
		return regiao;
	}
	public Integer getUnidadeRegional() {
		return unidadeRegional;
	}
	public Integer getLocalidade() {
		return localidade;
	}
	public Integer getSetor() {
		return setor;
	}
	public Integer getBairro() {
		return bairro;
	}
	public Integer getLogradouro() {
		return logradouro;
	}
	public Integer getMunicipio() {
		return municipio;
	}
	public Date getDatahorasolicitacao() {
		return datahorasolicitacao;
	}
	public Date getDatahorafimexecucao() {
		return datahorafimexecucao;
	}
	public Date getDatadia() {
		return datadia;
	}
	public Double getQtdHorasDia() {
		return qtdHorasDia;
	}
	public Double getQtdPerdaDia() {
		return qtdPerdaDia;
	}
	public Double getValorPerda() {
		return valorPerda;
	}
	public String getLatitude() {
		return latitude;
	}
	public String getLongitude() {
		return longitude;
	}
	@Id
	@NotBlank(message="{notblank}")	
	private int idVaz;
	@Column
	private Integer numerosolicitacao;
	@Column
	private Integer tiposolicitacao;
	@Column
	private Integer codespecificacao;
	@Column
	private Integer regiao;
	@Column
	private Integer unidadeRegional;
	@Column
	private Integer localidade;
	@Column
	private Integer setor;
	@Column
	private Integer bairro;
	@Column
	private Integer logradouro;
	@Column
	private Integer municipio;
	@Column
	private Date datahorasolicitacao;
	@Column
	private Date datahorafimexecucao;
	@Column
	private Date datadia;
	@Column
	private Double qtdHorasDia;
	@Column
	private Double qtdPerdaDia;
	@Column
	private Double valorPerda;
	@Column
	private String latitude;
	@Column
	private String longitude;
	
     //private Set fatos = new HashSet(0);
/*
    public DimensaoVazamento() {
    }

	
    public DimensaoVazamento(int idVazamento) {
        this.idVazamento = idVazamento;
    }
    public DimensaoVazamento(int idVazamento, DimensaoTempo dimensaoTempo, DofLocalidade dofLocalidade, DofRegiao dofRegiao, DofUnidaderegional dofUnidaderegional, Integer tiposolicitacao, Integer codespecificacao, Integer setor, Integer bairro, Integer logradouro, Integer municipio, Date datahorasolicitacao, Date datahorafimexecucao, Double qtdHorasDia, Double qtdPerdaDia, Double valorPerda, String latitude, String longitude, Set fatos) {
       this.idVazamento = idVazamento;
       this.dimensaoTempo = dimensaoTempo;
       this.dofLocalidade = dofLocalidade;
       this.dofRegiao = dofRegiao;
       this.dofUnidaderegional = dofUnidaderegional;
       this.tiposolicitacao = tiposolicitacao;
       this.codespecificacao = codespecificacao;
       this.setor = setor;
       this.bairro = bairro;
       this.logradouro = logradouro;
       this.municipio = municipio;
       this.datahorasolicitacao = datahorasolicitacao;
       this.datahorafimexecucao = datahorafimexecucao;
       this.qtdHorasDia = qtdHorasDia;
       this.qtdPerdaDia = qtdPerdaDia;
       this.valorPerda = valorPerda;
       this.latitude = latitude;
       this.longitude = longitude;
//       this.fatos = fatos;
    }
   
    public int getIdVazamento() {
        return this.idVazamento;
    }
    
    public void setIdVazamento(int idVazamento) {
        this.idVazamento = idVazamento;
    }
    public DimensaoTempo getDimensaoTempo() {
        return this.dimensaoTempo;
    }
    
    public void setDimensaoTempo(DimensaoTempo dimensaoTempo) {
        this.dimensaoTempo = dimensaoTempo;
    }
    public DofLocalidade getDofLocalidade() {
        return this.dofLocalidade;
    }
    
    public void setDofLocalidade(DofLocalidade dofLocalidade) {
        this.dofLocalidade = dofLocalidade;
    }
    public DofRegiao getDofRegiao() {
        return this.dofRegiao;
    }
    
    public void setDofRegiao(DofRegiao dofRegiao) {
        this.dofRegiao = dofRegiao;
    }
    public DofUnidaderegional getDofUnidaderegional() {
        return this.dofUnidaderegional;
    }
    
    public void setDofUnidaderegional(DofUnidaderegional dofUnidaderegional) {
        this.dofUnidaderegional = dofUnidaderegional;
    }
    public Integer getTiposolicitacao() {
        return this.tiposolicitacao;
    }
    
    public void setTiposolicitacao(Integer tiposolicitacao) {
        this.tiposolicitacao = tiposolicitacao;
    }
    public Integer getCodespecificacao() {
        return this.codespecificacao;
    }
    
    public void setCodespecificacao(Integer codespecificacao) {
        this.codespecificacao = codespecificacao;
    }
    public Integer getSetor() {
        return this.setor;
    }
    
    public void setSetor(Integer setor) {
        this.setor = setor;
    }
    public Integer getBairro() {
        return this.bairro;
    }
    
    public void setBairro(Integer bairro) {
        this.bairro = bairro;
    }
    public Integer getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(Integer logradouro) {
        this.logradouro = logradouro;
    }
    public Integer getMunicipio() {
        return this.municipio;
    }
    
    public void setMunicipio(Integer municipio) {
        this.municipio = municipio;
    }
    public Date getDatahorasolicitacao() {
        return this.datahorasolicitacao;
    }
    
    public void setDatahorasolicitacao(Date datahorasolicitacao) {
        this.datahorasolicitacao = datahorasolicitacao;
    }
    public Date getDatahorafimexecucao() {
        return this.datahorafimexecucao;
    }
    
    public void setDatahorafimexecucao(Date datahorafimexecucao) {
        this.datahorafimexecucao = datahorafimexecucao;
    }
    public Double getQtdHorasDia() {
        return this.qtdHorasDia;
    }
    
    public void setQtdHorasDia(Double qtdHorasDia) {
        this.qtdHorasDia = qtdHorasDia;
    }
    public Double getQtdPerdaDia() {
        return this.qtdPerdaDia;
    }
    
    public void setQtdPerdaDia(Double qtdPerdaDia) {
        this.qtdPerdaDia = qtdPerdaDia;
    }
    public Double getValorPerda() {
        return this.valorPerda;
    }
    
    public void setValorPerda(Double valorPerda) {
        this.valorPerda = valorPerda;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

*/


}


