package perdas.model;
// Generated 22/02/2019 16:25:43 by Hibernate Tools 4.3.1


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.NotBlank;

/**
 * DimensaoServico generated by hbm2java
 */
@Entity(name="tipo_servico")
public class TipoServico  implements Serializable {

	 private static final long serialVersionUID = 1L;
	 
	 public int getIdServico() {
		return idServico;
	}
	public Integer getSolicitacao() {
		return tipoServico;
	}
	public String getDescSolicitacao() {
		return descServico;
	}
	public Integer getEspecificacao() {
		return codEspecificacao;
	}
	public String getDescEspecificacao() {
		return descEspecificacao;
	}
	@Id
	 @NotBlank(message="{notblank}")	
     private int idServico;
     @Column
     private Integer tipoServico;
     @Column
     private String descServico;
     @Column
     private Integer codEspecificacao;
     @Column
     private String descEspecificacao;
     
 /*    
    public DimensaoServico() {
    }

	
    public DimensaoServico(int idServico) {
        this.idServico = idServico;
    }
    public DimensaoServico(int idServico, Integer solicitacao, String descSolicitacao, Integer especificacao, String descEspecificacao, Set fatos) {
       this.idServico = idServico;
       this.solicitacao = solicitacao;
       this.descSolicitacao = descSolicitacao;
       this.especificacao = especificacao;
       this.descEspecificacao = descEspecificacao;
       this.fatos = fatos;
    }
   
    public int getIdServico() {
        return this.idServico;
    }
    
    public void setIdServico(int idServico) {
        this.idServico = idServico;
    }
    public Integer getSolicitacao() {
        return this.solicitacao;
    }
    
    public void setSolicitacao(Integer solicitacao) {
        this.solicitacao = solicitacao;
    }
    public String getDescSolicitacao() {
        return this.descSolicitacao;
    }
    
    public void setDescSolicitacao(String descSolicitacao) {
        this.descSolicitacao = descSolicitacao;
    }
    public Integer getEspecificacao() {
        return this.especificacao;
    }
    
    public void setEspecificacao(Integer especificacao) {
        this.especificacao = especificacao;
    }
    public String getDescEspecificacao() {
        return this.descEspecificacao;
    }
    
    public void setDescEspecificacao(String descEspecificacao) {
        this.descEspecificacao = descEspecificacao;
    }
    public Set getFatos() {
        return this.fatos;
    }
    
    public void setFatos(Set fatos) {
        this.fatos = fatos;
    }

*/


}


