package perdas.model;
// Generated 22/02/2019 16:25:43 by Hibernate Tools 4.3.1


import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.validation.constraints.NotBlank;

/**
 * DimensaoOrganizacional generated by hbm2java
 */
@Entity(name="unidade_organizacional")
public class UnidadeOrganizacional  implements Serializable {

	private static final long serialVersionUID = 1L;

	public int getIdOrganizacao() {
		return idOrganizacao;
	}
	public Integer getEmpresa() {
		return empresa;
	}
	public String getSiglaEmpresa() {
		return siglaEmpresa;
	}
	public Integer getRegiao() {
		return regiao;
	}
	public String getNomeRegiao() {
		return nomeRegiao;
	}
	public Integer getUnidade() {
		return unidade;
	}
	public String getNomeUnidade() {
		return nomeUnidade;
	}
	public Integer getLocalidade() {
		return localidade;
	}
	public String getNomeLocalidade() {
		return nomeLocalidade;
	}
	public Integer getSetor() {
		return setor;
	}
	@Id
	@NotBlank(message="{notblank}")	
	private int idOrganizacao;
	@Column
	private Integer empresa;
	@Column
	private String siglaEmpresa;
	@Column
	private Integer regiao;
	@Column
	private String nomeRegiao;
	@Column
	private Integer unidade;
	@Column
	private String nomeUnidade;
	@Column
	private Integer localidade;
	@Column
	private String nomeLocalidade;
    @Column
	private Integer setor;

	
	/*
    public DimensaoOrganizacional() {
    }

	
    public DimensaoOrganizacional(int idOrganizacao) {
        this.idOrganizacao = idOrganizacao;
    }
    public DimensaoOrganizacional(int idOrganizacao, DofEmpresa dofEmpresa, DofLocalidade dofLocalidade, DofRegiao dofRegiao, DofUnidaderegional dofUnidaderegional, String siglaEmpresa, String nomeRegiao, String nomeUnidade, String nomeLocalidade, Integer setor, Set fatos) {
       this.idOrganizacao = idOrganizacao;
       this.dofEmpresa = dofEmpresa;
       this.dofLocalidade = dofLocalidade;
       this.dofRegiao = dofRegiao;
       this.dofUnidaderegional = dofUnidaderegional;
       this.siglaEmpresa = siglaEmpresa;
       this.nomeRegiao = nomeRegiao;
       this.nomeUnidade = nomeUnidade;
       this.nomeLocalidade = nomeLocalidade;
       this.setor = setor;
       this.fatos = fatos;
    }
   
    public int getIdOrganizacao() {
        return this.idOrganizacao;
    }
    
    public void setIdOrganizacao(int idOrganizacao) {
        this.idOrganizacao = idOrganizacao;
    }
    public DofEmpresa getDofEmpresa() {
        return this.dofEmpresa;
    }
    
    public void setDofEmpresa(DofEmpresa dofEmpresa) {
        this.dofEmpresa = dofEmpresa;
    }
    public DofLocalidade getDofLocalidade() {
        return this.dofLocalidade;
    }
    
    public void setDofLocalidade(DofLocalidade dofLocalidade) {
        this.dofLocalidade = dofLocalidade;
    }
    public DofRegiao getDofRegiao() {
        return this.dofRegiao;
    }
    
    public void setDofRegiao(DofRegiao dofRegiao) {
        this.dofRegiao = dofRegiao;
    }
    public DofUnidaderegional getDofUnidaderegional() {
        return this.dofUnidaderegional;
    }
    
    public void setDofUnidaderegional(DofUnidaderegional dofUnidaderegional) {
        this.dofUnidaderegional = dofUnidaderegional;
    }
    public String getSiglaEmpresa() {
        return this.siglaEmpresa;
    }
    
    public void setSiglaEmpresa(String siglaEmpresa) {
        this.siglaEmpresa = siglaEmpresa;
    }
    public String getNomeRegiao() {
        return this.nomeRegiao;
    }
    
    public void setNomeRegiao(String nomeRegiao) {
        this.nomeRegiao = nomeRegiao;
    }
    public String getNomeUnidade() {
        return this.nomeUnidade;
    }
    
    public void setNomeUnidade(String nomeUnidade) {
        this.nomeUnidade = nomeUnidade;
    }
    public String getNomeLocalidade() {
        return this.nomeLocalidade;
    }
    
    public void setNomeLocalidade(String nomeLocalidade) {
        this.nomeLocalidade = nomeLocalidade;
    }
    public Integer getSetor() {
        return this.setor;
    }
    
    public void setSetor(Integer setor) {
        this.setor = setor;
    }
    public Set getFatos() {
        return this.fatos;
    }
    
    public void setFatos(Set fatos) {
        this.fatos = fatos;
    }

*/


}


